title: Planty
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
favicon: images/favicon.png
logo_dark: images/logo.svg
logo_light: images/logo-white.svg
hamburger_background_image: /images/leaf-light-grey.svg
bg_image_primary: /images/header.jpg
bg_image_secondary: /images/leaf-light-grey.svg
bg_image_product: /images/leaf.svg
snipcart_api_key: ''
footer_text: Copyright 2020 Planty Inc. All rights reserved.
palette: green
palettes:
  green:
    sass:
      default: '#FFFFFF'
      light: '#F0F0F0'
      medium: '#6B797A'
      dark: '#384647'
      active: '#88DD9B'
      active_light: '#C0FDB6'
      active_medium: '#5C9174'
      active_dark: '#547567'
      dark_grey: '#273132'
      light_grey: '#6B797A'
      bg_image_cart: /images/leaf-light-grey.svg
  cyan:
    sass:
      default: '#FFFFFF'
      light: '#F0F4F8'
      medium: '#627D98'
      dark: '#334E68'
      active: '#54D1DB'
      active_light: '#BEF8FD'
      active_medium: '#38BEC9'
      active_dark: '#14919B'
      dark_grey: '#243B53'
      light_grey: '#627D98'
      bg_image_cart: /images/leaf-light-grey.svg
  yellow:
    sass:
      default: '#FFFFFF'
      light: '#FAF9F7'
      medium: '#857F72'
      dark: '#423D33'
      active: '#F0B429'
      active_light: '#FADB5F'
      active_medium: '#F7C948'
      active_dark: '#E99917'
      dark_grey: '#27241D'
      light_grey: '#625D52'
      bg_image_cart: /images/leaf-light-grey.svg
main_menu:
  - title: Store
    url: /store
    style: link
  - title: About
    url: /about
    style: link
  - title: FAQ
    url: /faq
    style: link
sass:
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
